"""Complete variable snapshot for the nine monthly-batched CDS collections.

Checked 2026-09-12 against public CDS retrieve/v1/processes/{collection} schemas.
CDS names/availability: https://cds.climate.copernicus.eu/api/retrieve/v1/processes
Parameter associations: https://confluence.ecmwf.int/pages/viewpage.action?pageId=239340673
ERA5-Land: https://confluence.ecmwf.int/pages/viewpage.action?pageId=505384848
Official GRIB names: ECMWF ecCodes revision 783dddf785d3e7208f5724ccdd6dedccdf0a4063,
https://github.com/ecmwf/eccodes/tree/783dddf785d3e7208f5724ccdd6dedccdf0a4063/definitions

Known documentation corrections: mwd2 is direction (not period), p2ps is
swell (not wind waves), and parameter 165/166 uses 10u/10v also for Land.
Snow depth differs: ERA5 sd is water equivalent; Land sde is geometric depth.
This snapshot records variable presence, not all product/date constraints.
"""

# (official short name, CDS variable name, parameter ID, collection IDs)
VARIABLE_CATALOGUE = (
    ('100u', '100m_u_component_of_wind', 228246, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('100v', '100m_v_component_of_wind', 228247, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('10fg', '10m_wind_gust_since_previous_post_processing', 49, ('reanalysis-era5-single-levels', 'derived-era5-single-levels-daily-statistics')),
    ('10si', '10m_wind_speed', 207, ('reanalysis-era5-single-levels-monthly-means',)),
    ('10u', '10m_u_component_of_wind', 165, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('10v', '10m_v_component_of_wind', 166, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('2d', '2m_dewpoint_temperature', 168, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('2t', '2m_temperature', 167, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('alnid', 'near_ir_albedo_for_diffuse_radiation', 18, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('alnip', 'near_ir_albedo_for_direct_radiation', 17, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('aluvd', 'uv_visible_albedo_for_diffuse_radiation', 16, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('aluvp', 'uv_visible_albedo_for_direct_radiation', 15, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('anor', 'angle_of_sub_gridscale_orography', 162, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('asn', 'snow_albedo', 32, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('avg_cpr', 'mean_convective_precipitation_rate', 235030, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_csfr', 'mean_convective_snowfall_rate', 235056, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_esrwe', 'mean_snow_evaporation_rate', 235023, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_ibld', 'mean_boundary_layer_dissipation', 235032, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_ie', 'mean_evaporation_rate', 235043, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_iegwss', 'mean_eastward_gravity_wave_surface_stress', 235045, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_iews', 'mean_eastward_turbulent_surface_stress', 235041, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_igwd', 'mean_gravity_wave_dissipation', 235047, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_ilspf', 'mean_large_scale_precipitation_fraction', 235026, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_imagss', 'mean_magnitude_of_turbulent_surface_stress', 235025, ('reanalysis-era5-single-levels-monthly-means',)),
    ('avg_ingwss', 'mean_northward_gravity_wave_surface_stress', 235046, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_inss', 'mean_northward_turbulent_surface_stress', 235042, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_ishf', 'mean_surface_sensible_heat_flux', 235033, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_lsprate', 'mean_large_scale_precipitation_rate', 235029, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_lssfr', 'mean_large_scale_snowfall_rate', 235057, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_pevr', 'mean_potential_evaporation_rate', 235070, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_rorwe', 'mean_runoff_rate', 235048, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_sdirswrf', 'mean_surface_direct_short_wave_radiation_flux', 235058, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_sdirswrfcs', 'mean_surface_direct_short_wave_radiation_flux_clear_sky', 235059, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_sdlwrf', 'mean_surface_downward_long_wave_radiation_flux', 235036, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_sdlwrfcs', 'mean_surface_downward_long_wave_radiation_flux_clear_sky', 235069, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_sdswrf', 'mean_surface_downward_short_wave_radiation_flux', 235035, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_sdswrfcs', 'mean_surface_downward_short_wave_radiation_flux_clear_sky', 235068, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_sduvrf', 'mean_surface_downward_uv_radiation_flux', 235027, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_slhtf', 'mean_surface_latent_heat_flux', 235034, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_smr', 'mean_snowmelt_rate', 235024, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_snlwrf', 'mean_surface_net_long_wave_radiation_flux', 235038, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_snlwrfcs', 'mean_surface_net_long_wave_radiation_flux_clear_sky', 235052, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_snswrf', 'mean_surface_net_short_wave_radiation_flux', 235037, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_snswrfcs', 'mean_surface_net_short_wave_radiation_flux_clear_sky', 235051, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_ssurfror', 'mean_sub_surface_runoff_rate', 235021, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_surfror', 'mean_surface_runoff_rate', 235020, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_tdswrf', 'mean_top_downward_short_wave_radiation_flux', 235053, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_tnlwrf', 'mean_top_net_long_wave_radiation_flux', 235040, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_tnlwrfcs', 'mean_top_net_long_wave_radiation_flux_clear_sky', 235050, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_tnswrf', 'mean_top_net_short_wave_radiation_flux', 235039, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_tnswrfcs', 'mean_top_net_short_wave_radiation_flux_clear_sky', 235049, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_tprate', 'mean_total_precipitation_rate', 235055, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_tsrwe', 'mean_snowfall_rate', 235031, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('avg_vimdf', 'mean_vertically_integrated_moisture_divergence', 235054, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('bfi', 'benjamin_feir_index', 140253, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('bld', 'boundary_layer_dissipation', 145, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('blh', 'boundary_layer_height', 159, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('cape', 'convective_available_potential_energy', 59, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('cbh', 'cloud_base_height', 228023, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('cc', 'fraction_of_cloud_cover', 248, ('reanalysis-era5-pressure-levels', 'reanalysis-era5-pressure-levels-monthly-means', 'derived-era5-pressure-levels-daily-statistics')),
    ('cdir', 'clear_sky_direct_solar_radiation_at_surface', 228022, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('cdww', 'coefficient_of_drag_with_waves', 140233, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('chnk', 'charnock', 148, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('ci', 'sea_ice_cover', 31, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('cin', 'convective_inhibition', 228001, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('ciwc', 'specific_cloud_ice_water_content', 247, ('reanalysis-era5-pressure-levels', 'reanalysis-era5-pressure-levels-monthly-means', 'derived-era5-pressure-levels-daily-statistics')),
    ('cl', 'lake_cover', 26, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('clwc', 'specific_cloud_liquid_water_content', 246, ('reanalysis-era5-pressure-levels', 'reanalysis-era5-pressure-levels-monthly-means', 'derived-era5-pressure-levels-daily-statistics')),
    ('cp', 'convective_precipitation', 143, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('crr', 'convective_rain_rate', 228218, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('crwc', 'specific_rain_water_content', 75, ('reanalysis-era5-pressure-levels', 'reanalysis-era5-pressure-levels-monthly-means', 'derived-era5-pressure-levels-daily-statistics')),
    ('csf', 'convective_snowfall', 239, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('csfr', 'convective_snowfall_rate_water_equivalent', 228220, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('cswc', 'specific_snow_water_content', 76, ('reanalysis-era5-pressure-levels', 'reanalysis-era5-pressure-levels-monthly-means', 'derived-era5-pressure-levels-daily-statistics')),
    ('cvh', 'high_vegetation_cover', 28, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('cvl', 'low_vegetation_cover', 27, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('d', 'divergence', 155, ('reanalysis-era5-pressure-levels', 'reanalysis-era5-pressure-levels-monthly-means', 'derived-era5-pressure-levels-daily-statistics')),
    ('dctb', 'duct_base_height', 228017, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('deg0l', 'zero_degree_level', 228024, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('dl', 'lake_depth', 228007, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('dl', 'lake_total_depth', 228007, ('reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('dndza', 'mean_vertical_gradient_of_refractivity_inside_trapping_layer', 228016, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('dndzn', 'minimum_vertical_gradient_of_refractivity_inside_trapping_layer', 228015, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('dwi', 'ocean_surface_stress_equivalent_10m_neutral_wind_direction', 140249, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('dwps', 'wave_spectral_directional_width_for_swell', 140228, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('dwww', 'wave_spectral_directional_width_for_wind_waves', 140225, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('e', 'evaporation', 182, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('e', 'total_evaporation', 182, ('reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('es', 'snow_evaporation', 44, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('evabs', 'evaporation_from_bare_soil', 228101, ('reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('evaow', 'evaporation_from_open_water_surfaces_excluding_oceans', 228102, ('reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('evatc', 'evaporation_from_the_top_of_canopy', 228100, ('reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('evavt', 'evaporation_from_vegetation_transpiration', 228103, ('reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('ewss', 'eastward_turbulent_surface_stress', 180, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('fal', 'forecast_albedo', 243, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('fdir', 'total_sky_direct_solar_radiation_at_surface', 228021, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('flsr', 'forecast_logarithm_of_surface_roughness_for_heat', 245, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('fsr', 'forecast_surface_roughness', 244, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('glm', 'glacier_mask', 260294, ('reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('gwd', 'gravity_wave_dissipation', 197, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('hcc', 'high_cloud_cover', 188, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('hmax', 'maximum_individual_wave_height', 140218, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('i10fg', 'instantaneous_10m_wind_gust', 228029, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('ie', 'instantaneous_moisture_flux', 232, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('iews', 'instantaneous_eastward_turbulent_surface_stress', 229, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('ilspf', 'instantaneous_large_scale_surface_precipitation_fraction', 228217, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('inss', 'instantaneous_northward_turbulent_surface_stress', 230, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('ishf', 'instantaneous_surface_sensible_heat_flux', 231, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('isor', 'anisotropy_of_sub_gridscale_orography', 161, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('istl1', 'ice_temperature_layer_1', 35, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('istl2', 'ice_temperature_layer_2', 36, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('istl3', 'ice_temperature_layer_3', 37, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('istl4', 'ice_temperature_layer_4', 38, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('kx', 'k_index', 260121, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('lai_hv', 'leaf_area_index_high_vegetation', 67, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('lai_lv', 'leaf_area_index_low_vegetation', 66, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('lblt', 'lake_bottom_temperature', 228010, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('lcc', 'low_cloud_cover', 186, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('lgws', 'eastward_gravity_wave_surface_stress', 195, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('licd', 'lake_ice_depth', 228014, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('lict', 'lake_ice_temperature', 228013, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('lmld', 'lake_mix_layer_depth', 228009, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('lmlt', 'lake_mix_layer_temperature', 228008, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('lsf', 'large_scale_snowfall', 240, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('lshf', 'lake_shape_factor', 228012, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('lsm', 'land_sea_mask', 172, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('lsp', 'large_scale_precipitation', 142, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('lspf', 'large_scale_precipitation_fraction', 50, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('lsrr', 'large_scale_rain_rate', 228219, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('lssfr', 'large_scale_snowfall_rate_water_equivalent', 228221, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('ltlt', 'lake_total_layer_temperature', 228011, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('magss', 'magnitude_of_turbulent_surface_stress', 48, ('reanalysis-era5-single-levels-monthly-means',)),
    ('mcc', 'medium_cloud_cover', 187, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('mdts', 'mean_direction_of_total_swell', 140238, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('mdww', 'mean_direction_of_wind_waves', 140235, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('mgws', 'northward_gravity_wave_surface_stress', 196, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('mn2t', 'minimum_2m_temperature_since_previous_post_processing', 202, ('reanalysis-era5-single-levels', 'derived-era5-single-levels-daily-statistics')),
    ('mntpr', 'minimum_total_precipitation_rate_since_previous_post_processing', 228227, ('reanalysis-era5-single-levels', 'derived-era5-single-levels-daily-statistics')),
    ('mp1', 'mean_wave_period_based_on_first_moment', 140220, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('mp2', 'mean_zero_crossing_wave_period', 140221, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('mpts', 'mean_period_of_total_swell', 140239, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('mpww', 'mean_period_of_wind_waves', 140236, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('msl', 'mean_sea_level_pressure', 151, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('msqs', 'mean_square_slope_of_waves', 140244, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('mwd', 'mean_wave_direction', 140230, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('mwd1', 'mean_wave_direction_of_first_swell_partition', 140122, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('mwd2', 'mean_wave_direction_of_second_swell_partition', 140125, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('mwd3', 'mean_wave_direction_of_third_swell_partition', 140128, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('mwp', 'mean_wave_period', 140232, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('mwp1', 'mean_wave_period_of_first_swell_partition', 140123, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('mwp2', 'mean_wave_period_of_second_swell_partition', 140126, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('mwp3', 'mean_wave_period_of_third_swell_partition', 140129, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('mx2t', 'maximum_2m_temperature_since_previous_post_processing', 201, ('reanalysis-era5-single-levels', 'derived-era5-single-levels-daily-statistics')),
    ('mxtpr', 'maximum_total_precipitation_rate_since_previous_post_processing', 228226, ('reanalysis-era5-single-levels', 'derived-era5-single-levels-daily-statistics')),
    ('nsss', 'northward_turbulent_surface_stress', 181, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('o3', 'ozone_mass_mixing_ratio', 203, ('reanalysis-era5-pressure-levels', 'reanalysis-era5-pressure-levels-monthly-means', 'derived-era5-pressure-levels-daily-statistics')),
    ('p1ps', 'mean_wave_period_based_on_first_moment_for_swell', 140226, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('p1ww', 'mean_wave_period_based_on_first_moment_for_wind_waves', 140223, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('p2ps', 'mean_wave_period_based_on_second_moment_for_swell', 140227, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('p2ww', 'mean_wave_period_based_on_second_moment_for_wind_waves', 140224, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('pev', 'potential_evaporation', 228251, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('phiaw', 'normalized_energy_flux_into_waves', 140211, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('phioc', 'normalized_energy_flux_into_ocean', 140212, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('pp1d', 'peak_wave_period', 140231, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('ptype', 'precipitation_type', 260015, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('pv', 'potential_vorticity', 60, ('reanalysis-era5-pressure-levels', 'reanalysis-era5-pressure-levels-monthly-means', 'derived-era5-pressure-levels-daily-statistics')),
    ('q', 'specific_humidity', 133, ('reanalysis-era5-pressure-levels', 'reanalysis-era5-pressure-levels-monthly-means', 'derived-era5-pressure-levels-daily-statistics')),
    ('r', 'relative_humidity', 157, ('reanalysis-era5-pressure-levels', 'reanalysis-era5-pressure-levels-monthly-means', 'derived-era5-pressure-levels-daily-statistics')),
    ('rhoao', 'air_density_over_the_oceans', 140209, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('ro', 'runoff', 205, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('rsn', 'snow_density', 33, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('sd', 'snow_depth', 141, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('sd', 'snow_depth_water_equivalent', 141, ('reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('sde', 'snow_depth', 3066, ('reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('sdfor', 'standard_deviation_of_filtered_subgrid_orography', 74, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('sdor', 'standard_deviation_of_orography', 160, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('sf', 'snowfall', 144, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('shts', 'significant_height_of_total_swell', 140237, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('shww', 'significant_height_of_wind_waves', 140234, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('skt', 'skin_temperature', 235, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('slhf', 'surface_latent_heat_flux', 147, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('slor', 'slope_of_sub_gridscale_orography', 163, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('slt', 'soil_type', 43, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('smlt', 'snowmelt', 45, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('snowc', 'snow_cover', 260038, ('reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('sp', 'surface_pressure', 134, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('src', 'skin_reservoir_content', 198, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('sro', 'surface_runoff', 8, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('sshf', 'surface_sensible_heat_flux', 146, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('ssr', 'surface_net_solar_radiation', 176, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('ssrc', 'surface_net_solar_radiation_clear_sky', 210, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('ssrd', 'surface_solar_radiation_downwards', 169, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('ssrdc', 'surface_solar_radiation_downward_clear_sky', 228129, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('ssro', 'sub_surface_runoff', 9, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('sst', 'sea_surface_temperature', 34, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('stl1', 'soil_temperature_level_1', 139, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('stl2', 'soil_temperature_level_2', 170, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('stl3', 'soil_temperature_level_3', 183, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('stl4', 'soil_temperature_level_4', 236, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('str', 'surface_net_thermal_radiation', 177, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('strc', 'surface_net_thermal_radiation_clear_sky', 211, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('strd', 'surface_thermal_radiation_downwards', 175, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('strdc', 'surface_thermal_radiation_downward_clear_sky', 228130, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('swh', 'significant_height_of_combined_wind_waves_and_swell', 140229, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('swh1', 'significant_wave_height_of_first_swell_partition', 140121, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('swh2', 'significant_wave_height_of_second_swell_partition', 140124, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('swh3', 'significant_wave_height_of_third_swell_partition', 140127, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('swvl1', 'volumetric_soil_water_layer_1', 39, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('swvl2', 'volumetric_soil_water_layer_2', 40, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('swvl3', 'volumetric_soil_water_layer_3', 41, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('swvl4', 'volumetric_soil_water_layer_4', 42, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('t', 'temperature', 130, ('reanalysis-era5-pressure-levels', 'reanalysis-era5-pressure-levels-monthly-means', 'derived-era5-pressure-levels-daily-statistics')),
    ('tauoc', 'normalized_stress_into_ocean', 140214, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('tcc', 'total_cloud_cover', 164, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('tciw', 'total_column_cloud_ice_water', 79, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('tclw', 'total_column_cloud_liquid_water', 78, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('tco3', 'total_column_ozone', 206, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('tcrw', 'total_column_rain_water', 228089, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('tcslw', 'total_column_supercooled_liquid_water', 228088, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('tcsw', 'total_column_snow_water', 228090, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('tcw', 'total_column_water', 136, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('tcwv', 'total_column_water_vapour', 137, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('tisr', 'toa_incident_solar_radiation', 212, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('tmax', 'period_corresponding_to_maximum_individual_wave_height', 140217, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('totalx', 'total_totals_index', 260123, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('tp', 'total_precipitation', 228, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('tplb', 'trapping_layer_base_height', 228018, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('tplt', 'trapping_layer_top_height', 228019, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('tsn', 'temperature_of_snow_layer', 238, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means', 'derived-era5-land-daily-statistics')),
    ('tsr', 'top_net_solar_radiation', 178, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('tsrc', 'top_net_solar_radiation_clear_sky', 208, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('ttr', 'top_net_thermal_radiation', 179, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('ttrc', 'top_net_thermal_radiation_clear_sky', 209, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('tvh', 'type_of_high_vegetation', 30, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('tvl', 'type_of_low_vegetation', 29, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('u', 'u_component_of_wind', 131, ('reanalysis-era5-pressure-levels', 'reanalysis-era5-pressure-levels-monthly-means', 'derived-era5-pressure-levels-daily-statistics')),
    ('u10n', '10m_u_component_of_neutral_wind', 228131, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('ust', 'u_component_stokes_drift', 140215, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('uvb', 'downward_uv_radiation_at_the_surface', 57, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('v', 'v_component_of_wind', 132, ('reanalysis-era5-pressure-levels', 'reanalysis-era5-pressure-levels-monthly-means', 'derived-era5-pressure-levels-daily-statistics')),
    ('v10n', '10m_v_component_of_neutral_wind', 228132, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('viec', 'vertical_integral_of_energy_conversion', 162064, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vigd', 'vertical_integral_of_divergence_of_geopotential_flux', 162085, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vige', 'vertical_integral_of_eastward_geopotential_flux', 162073, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vign', 'vertical_integral_of_northward_geopotential_flux', 162074, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('viiwd', 'vertical_integral_of_divergence_of_cloud_frozen_water_flux', 162080, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('viiwe', 'vertical_integral_of_eastward_cloud_frozen_water_flux', 162090, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('viiwn', 'vertical_integral_of_northward_cloud_frozen_water_flux', 162091, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vike', 'vertical_integral_of_kinetic_energy', 162059, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('viked', 'vertical_integral_of_divergence_of_kinetic_energy_flux', 162082, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vikee', 'vertical_integral_of_eastward_kinetic_energy_flux', 162067, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('viken', 'vertical_integral_of_northward_kinetic_energy_flux', 162068, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vilwd', 'vertical_integral_of_divergence_of_cloud_liquid_water_flux', 162079, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vilwe', 'vertical_integral_of_eastward_cloud_liquid_water_flux', 162088, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vilwn', 'vertical_integral_of_northward_cloud_liquid_water_flux', 162089, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vima', 'vertical_integral_of_mass_of_atmosphere', 162053, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vimad', 'vertical_integral_of_divergence_of_mass_flux', 162081, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vimae', 'vertical_integral_of_eastward_mass_flux', 162065, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('viman', 'vertical_integral_of_northward_mass_flux', 162066, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vimat', 'vertical_integral_of_mass_tendency', 162092, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vimd', 'vertically_integrated_moisture_divergence', 213, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vimdf', 'vertical_integral_of_divergence_of_moisture_flux', 162084, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('viozd', 'vertical_integral_of_divergence_of_ozone_flux', 162087, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vioze', 'vertical_integral_of_eastward_ozone_flux', 162077, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('viozn', 'vertical_integral_of_northward_ozone_flux', 162078, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vipie', 'vertical_integral_of_potential_and_internal_energy', 162061, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vipile', 'vertical_integral_of_potential_internal_and_latent_energy', 162062, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vit', 'vertical_integral_of_temperature', 162054, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vited', 'vertical_integral_of_divergence_of_total_energy_flux', 162086, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vitee', 'vertical_integral_of_eastward_total_energy_flux', 162075, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('viten', 'vertical_integral_of_northward_total_energy_flux', 162076, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vithe', 'vertical_integral_of_thermal_energy', 162060, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vithed', 'vertical_integral_of_divergence_of_thermal_energy_flux', 162083, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vithee', 'vertical_integral_of_eastward_heat_flux', 162069, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vithen', 'vertical_integral_of_northward_heat_flux', 162070, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vitoe', 'vertical_integral_of_total_energy', 162063, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('viwve', 'vertical_integral_of_eastward_water_vapour_flux', 162071, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('viwvn', 'vertical_integral_of_northward_water_vapour_flux', 162072, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('vo', 'vorticity', 138, ('reanalysis-era5-pressure-levels', 'reanalysis-era5-pressure-levels-monthly-means', 'derived-era5-pressure-levels-daily-statistics')),
    ('vst', 'v_component_stokes_drift', 140216, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('w', 'vertical_velocity', 135, ('reanalysis-era5-pressure-levels', 'reanalysis-era5-pressure-levels-monthly-means', 'derived-era5-pressure-levels-daily-statistics')),
    ('wdw', 'wave_spectral_directional_width', 140222, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('wind', 'ocean_surface_stress_equivalent_10m_neutral_wind_speed', 140245, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('wmb', 'model_bathymetry', 140219, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('wsk', 'wave_spectral_kurtosis', 140252, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('wsp', 'wave_spectral_peakedness', 140254, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('wss', 'wave_spectral_skewness', 140207, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('wstar', 'free_convective_velocity_over_the_oceans', 140208, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
    ('z', 'geopotential', 129, ('reanalysis-era5-single-levels', 'reanalysis-era5-pressure-levels', 'reanalysis-era5-single-levels-monthly-means', 'reanalysis-era5-pressure-levels-monthly-means', 'derived-era5-single-levels-daily-statistics', 'derived-era5-pressure-levels-daily-statistics', 'reanalysis-era5-land', 'reanalysis-era5-land-monthly-means')),
    ('zust', 'friction_velocity', 228003, ('reanalysis-era5-single-levels', 'reanalysis-era5-single-levels-monthly-means', 'derived-era5-single-levels-daily-statistics')),
)

# Older official names still used in the ERA5 parameter documentation.
DOCUMENTED_GRIB_NAMES = {'mbld': 'avg_ibld', 'mcpr': 'avg_cpr', 'mcsr': 'avg_csfr', 'megwss': 'avg_iegwss', 'mer': 'avg_ie', 'metss': 'avg_iews', 'mgwd': 'avg_igwd', 'mlspf': 'avg_ilspf', 'mlspr': 'avg_lsprate', 'mlssr': 'avg_lssfr', 'mmtss': 'avg_imagss', 'mngwss': 'avg_ingwss', 'mntss': 'avg_inss', 'mper': 'avg_pevr', 'mror': 'avg_rorwe', 'msdrswrf': 'avg_sdirswrf', 'msdrswrfcs': 'avg_sdirswrfcs', 'msdwlwrf': 'avg_sdlwrf', 'msdwlwrfcs': 'avg_sdlwrfcs', 'msdwswrf': 'avg_sdswrf', 'msdwswrfcs': 'avg_sdswrfcs', 'msdwuvrf': 'avg_sduvrf', 'mser': 'avg_esrwe', 'mslhf': 'avg_slhtf', 'msmr': 'avg_smr', 'msnlwrf': 'avg_snlwrf', 'msnlwrfcs': 'avg_snlwrfcs', 'msnswrf': 'avg_snswrf', 'msnswrfcs': 'avg_snswrfcs', 'msr': 'avg_tsrwe', 'msror': 'avg_surfror', 'msshf': 'avg_ishf', 'mssror': 'avg_ssurfror', 'mtdwswrf': 'avg_tdswrf', 'mtnlwrf': 'avg_tnlwrf', 'mtnlwrfcs': 'avg_tnlwrfcs', 'mtnswrf': 'avg_tnswrf', 'mtnswrfcs': 'avg_tnswrfcs', 'mtpr': 'avg_tprate', 'mvimd': 'avg_vimdf', 'vitoed': 'vited', 'vitoee': 'vitee', 'vitoen': 'viten', 'viwvd': 'vimdf'}

DATASET_VARIABLES = {}
GRIB_VARIABLES = {}
for short, variable, parameter_id, datasets in VARIABLE_CATALOGUE:
    GRIB_VARIABLES.setdefault(short, variable)
    for dataset in datasets:
        DATASET_VARIABLES.setdefault(dataset, {})[short] = variable
for documented, current in DOCUMENTED_GRIB_NAMES.items():
    GRIB_VARIABLES[documented] = GRIB_VARIABLES[current]
    for selections in DATASET_VARIABLES.values():
        if current in selections:
            selections[documented] = selections[current]
